.\"
.\" @(#)dbdatabases.1 1.1  02/11/98 16:34:03  02/23/98 15:57:14
.\"
.TH DBDATABASES 1 "dbdatabases 1.1"
.SH NAME
dbdatabases \- prints a database information report
.SH SYNOPSIS
dbdatabases
.SH DESCRIPTION
.I Dbdatabases
will print a database information report containing: database name,
owner, dbspace location, creation date, and log status.
.SH SUPPORT
Send bug reports to Dave Snyder <dave@snide.com>
